id = "symbols"
name = "Symbols"
version = "1.0.0"
schema_version = 1
description = "A simple file icon theme"
repository = "https://github.com/sebastiandotdev/zed-symbols"
authors = ["Miguel Solorio <unknown@unknown.dev>"]
themes = []
icon_themes = ["icon_themes/symbols-icon-theme.json"]
languages = []
capabilities = []

[lib]

[grammars]

[language_servers]

[context_servers]

[slash_commands]

[indexed_docs_providers]
