# Menus
bindd = ALT, SPACE, Launch apps, exec, vicinae open
# bindd = SUPER, SPACE, Launch apps, exec, omarchy-launch-walker
bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu
bindd = SUPER CTRL, E, Emoji picker, exec, omarchy-launch-walker -m symbols
bindd = SUPER CTRL, C, Capture menu, exec, omarchy-menu capture
bindd = SUPER CTRL, O, Toggle menu, exec, omarchy-menu toggle
bindd = SUPER, ESCAPE, Power menu, exec, omarchy-menu system
bindld = , XF86PowerOff, Power menu, exec, omarchy-menu system
bindd = SUPER, K, Show key bindings, exec, omarchy-menu-keybindings
# bindd = , XF86Calculator, Calculator, exec, gnome-calculator

# Aesthetics
bindd = SUPER SHIFT, SPACE, Toggle top bar, exec, omarchy-toggle-waybar
bindd = SUPER CTRL, SPACE, Next background in theme, exec, omarchy-launch-walker -m menus:omarchyBackgroundSelector --width 800 --minheight 400
bindd = SUPER SHIFT CTRL, SPACE, Pick new theme, exec, omarchy-menu theme
bindd = SUPER, BACKSPACE, Toggle window transparency, exec, hyprctl dispatch setprop "address:$(hyprctl activewindow -j | jq -r '.address')" opaque toggle
bindd = SUPER SHIFT, BACKSPACE, Toggle workspace gaps, exec, omarchy-hyprland-workspace-toggle-gaps
bindd = SUPER CTRL, BACKSPACE, Toggle single-window square aspect, exec, omarchy-hyprland-window-single-square-aspect-toggle

# Notifications
bindd = SUPER, COMMA, Dismiss last notification, exec, swaync-client -C
bindd = SUPER CTRL, COMMA, Toggle silencing notifications, exec, swaync-client -d -sw

# Toggle idling
bindd = SUPER CTRL, I, Toggle locking on idle, exec, ~/.config/hypr/scripts/osd.sh idle-toggle

# Toggle nightlight
bindd = SUPER CTRL, N, Toggle nightlight, exec, ~/.config/hypr/scripts/osd.sh nightlight-toggle

# Toggle screensaver
bindd = SUPER CTRL, S, Toggle screensaver, exec, ~/.config/hypr/scripts/osd.sh screensaver-toggle

# Control Apple Display brightness
bindd = CTRL, F1, Apple Display brightness down, exec, omarchy-cmd-apple-display-brightness -5000
bindd = CTRL, F2, Apple Display brightness up, exec, omarchy-cmd-apple-display-brightness +5000
bindd = SHIFT CTRL, F2, Apple Display full brightness, exec, omarchy-cmd-apple-display-brightness +60000

# Captures
bindd = CTRL, Print, Screenrecording, exec, omarchy-menu screenrecord
bindd = , Print, Screenshot, exec, hyprshot -m output -m eDP-1 -o /tmp
bindd = SUPER, Print, Screenshot, exec, hyprshot -m region -o /tmp --raw | satty --filename -
bindd = ALT, Print, Color picking, exec, pkill hyprpicker || hyprpicker -a

# File sharing
# bindd = SUPER ALT, S, Share, exec, omarchy-menu share

# Others
bindd = SUPER CTRL, W, Open WiFi, exec, omarchy-launch-wifi
bindd = SUPER CTRL, B, Open Bluetooth, exec, omarchy-launch-bluetooth
