hl.on("hyprland.start", function()
  hl.exec_cmd("$HOME/.local/bin/hyprland-load-plugins")
  hl.exec_cmd("systemctl --user import-environment $(env | cut -d'=' -f 1)")
  hl.exec_cmd("dbus-update-activation-environment --systemd --all")
  hl.exec_cmd(o.launch("hypridle"))
  hl.exec_cmd(o.launch("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1"))
  hl.exec_cmd("omarchy-first-run")
  hl.exec_cmd("omarchy-powerprofiles-init")
  hl.exec_cmd(o.launch("udiskie --automount --no-notify --no-tray"))
  hl.exec_cmd("sleep 2 && omarchy-hook post-boot")
end)
