local function bind(keys, description, command, options)
  hl.unbind(keys)
  o.bind(keys, description, command, options)
end

bind("SUPER + K", "Show key bindings", "$HOME/.local/bin/omarchy-menu-keybindings")
bind("SHIFT + PRINT", "Region screenshot", "$HOME/.local/bin/area-screenshot")
bind("SUPER + ESCAPE", "Power menu", [[env OMARCHY_PATH=$HOME/.config/omarchy/quattro-bar-only omarchy-shell shell toggle omarchy.menu '{"menu":"system"}']])
bind("XF86PowerOff", "Power menu", [[env OMARCHY_PATH=$HOME/.config/omarchy/quattro-bar-only omarchy-shell shell toggle omarchy.menu '{"menu":"system"}']], { locked = true })

bind("SUPER + A", "Notification Center", "qs ipc -n -p ~/.config/omarchy/quattro-bar-only/shell call omarchy.bar closePopout; sleep 0.2; swaync-client -t -sw")
bind("SUPER + L", "Hyprlock", "hyprlock")
bind("SUPER + SHIFT + L", "Screensaver", "omarchy-launch-screensaver")
bind("SUPER + RETURN", "Terminal", [[uwsm app -- $TERMINAL --working-directory="$(omarchy-cmd-terminal-cwd)"]])
bind("SUPER + SHIFT + RETURN", "Alternative Terminal", "terax")
bind("SUPER + E", "Yazi", "uwsm app -- $TERMINAL -e yazi")
bind("SUPER + SHIFT + E", "File manager", "uwsm app -- nautilus --new-window")
bind("SUPER + W", "Browser", "flatpak run app.zen_browser.zen")
bind("SUPER + SHIFT + W", "Private Browser", "flatpak run app.zen_browser.zen --private-window")
bind("SUPER + R", "Activity", "uwsm app -- $TERMINAL -e btop")
bind("SUPER + SHIFT + R", "Mission Center", "flatpak run io.missioncenter.MissionCenter")
bind("SUPER + O", "Obsidian", [[omarchy-launch-or-focus obsidian "uwsm app -- obsidian -disable-gpu --enable-wayland-ime"]])
bind("SUPER + P", "SCRCPY", "scrcpy --serial=192.168.68.100:5555 --turn-screen-off --stay-awake --power-off-on-close")
bind("SUPER + SHIFT + P", "SCRCPY", "scrcpy --serial=192.168.68.100:5555 --stay-awake --power-off-on-close")
bind("SUPER + C", "Code Editor", "zeditor")
bind("SUPER + T", "T3 Code", "t3code-nightly")
bind("SUPER + D", "Discord", "flatpak run com.discordapp.Discord")
bind("SUPER + S", "Music", "spotify")
bind("SUPER + M", "kew", "uwsm app -- $TERMINAL -e kew")
bind("SUPER + SHIFT + M", "Cliamp", "uwsm app -- $TERMINAL -e cliamp")
bind("SUPER + G", "Gapless", "flatpak run com.github.neithern.g4music")
bind("SUPER + ALT + S", "Share", "localsend")
bind("SUPER + I", "Settings", [[fish -c "hyprmod"]])
bind("SUPER + H", "Hermes", "hermes desktop")
bind("SUPER + ALT + SPACE", "Confetti", "vicinae vicinae://launch/@esh/confetti/confetti")
bind("SUPER + X", "Dictation", "voxtype record toggle")

local repeat_locked = { locked = true, repeating = true }
bind("XF86AudioRaiseVolume", nil, "~/.config/hypr/scripts/osd.sh vol-up", repeat_locked)
bind("XF86AudioLowerVolume", nil, "~/.config/hypr/scripts/osd.sh vol-down", repeat_locked)
bind("XF86AudioMute", nil, "~/.config/hypr/scripts/osd.sh vol-mute", { locked = true })
bind("XF86AudioMicMute", nil, "~/.config/hypr/scripts/osd.sh mic-mute", { locked = true })
bind("ALT + XF86AudioRaiseVolume", nil, "~/.config/hypr/scripts/osd.sh vol-up 1", repeat_locked)
bind("ALT + XF86AudioLowerVolume", nil, "~/.config/hypr/scripts/osd.sh vol-down 1", repeat_locked)
bind("XF86MonBrightnessUp", nil, "~/.config/hypr/scripts/osd.sh bright-up", repeat_locked)
bind("XF86MonBrightnessDown", nil, "~/.config/hypr/scripts/osd.sh bright-down", repeat_locked)
bind("ALT + XF86MonBrightnessUp", nil, "~/.config/hypr/scripts/osd.sh bright-up 1", repeat_locked)
bind("ALT + XF86MonBrightnessDown", nil, "~/.config/hypr/scripts/osd.sh bright-down 1", repeat_locked)
bind("SUPER + PAGE_UP", nil, "~/.config/hypr/scripts/osd.sh bright-up", repeat_locked)
bind("SUPER + PAGE_DOWN", nil, "~/.config/hypr/scripts/osd.sh bright-down", repeat_locked)
bind("SUPER + ALT + PAGE_UP", nil, "~/.config/hypr/scripts/osd.sh bright-up 1", repeat_locked)
bind("SUPER + ALT + PAGE_DOWN", nil, "~/.config/hypr/scripts/osd.sh bright-down 1", repeat_locked)
bind("SHIFT + XF86MonBrightnessUp", nil, "~/.config/hypr/scripts/osd.sh bright-max", repeat_locked)
bind("SHIFT + XF86MonBrightnessDown", nil, "~/.config/hypr/scripts/osd.sh bright-min", repeat_locked)

bind("SUPER + ALT + T", "Show time", "~/.config/hypr/scripts/osd.sh time")
bind("SUPER + ALT + B", "Open Battery", "env OMARCHY_PATH=$HOME/.config/omarchy/quattro-bar-only omarchy-shell shell toggle omarchy.power")
bind("SUPER + CTRL + D", "Open Taildrop", "env OMARCHY_PATH=$HOME/.config/omarchy/quattro-bar-only omarchy-shell shell toggle taildrop")
bind("SUPER + code:49", "Workspace overview", "env OMARCHY_PATH=$HOME/.config/omarchy/quattro-bar-only omarchy-shell shell toggle omarchy-overview")

bind("ALT + LEFT", nil, [[hyprctl dispatch sendshortcut ", Home, activewindow"]])
bind("ALT + RIGHT", nil, [[hyprctl dispatch sendshortcut ", End, activewindow"]])
bind("ALT + SHIFT + LEFT", nil, [[hyprctl dispatch sendshortcut "SHIFT, Home, activewindow"]])
bind("ALT + SHIFT + RIGHT", nil, [[hyprctl dispatch sendshortcut "SHIFT, End, activewindow"]])
bind("ALT + BACKSPACE", nil, [[hyprctl dispatch sendshortcut "SHIFT, Home, activewindow"; hyprctl dispatch sendshortcut ", Delete, activewindow"]])
bind("ALT + DELETE", nil, [[hyprctl dispatch sendshortcut "SHIFT, End, activewindow"; hyprctl dispatch sendshortcut ", Delete, activewindow"]])
