$terminal = uwsm app -- $TERMINAL

bindd = SUPER, A, Notification Center, exec, swaync-client -t -sw
bindd = SUPER, L, Hyprlock, exec, hyprlock
bindd = SUPER SHIFT, L, Screensaver, exec, omarchy-launch-screensaver
bindd = SUPER, return, Terminal, exec, $terminal --working-directory="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER, E, Yazi, exec, $terminal yazi
bindd = SUPER SHIFT, E, File manager, exec, uwsm app -- nautilus --new-window
bindd = SUPER, W, Browser, exec, flatpak run app.zen_browser.zen
bindd = SUPER SHIFT, W, Private Browser, exec, flatpak run app.zen_browser.zen --private-window
bindd = SUPER, S, Music, exec, flatpak run com.spotify.Client
bindd = SUPER, T, Activity, exec, $terminal -e btop
bindd = SUPER SHIFT, T, Mission Center, exec, flatpak run io.missioncenter.MissionCenter
# bindd = SUPER, M, Minecraft, exec, java -jar /home/eshayat/Documents/minecraft.jar
bindd = SUPER, O, Obsidian, exec, omarchy-launch-or-focus obsidian "uwsm app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER, C, Code Editor, exec, code
bindd = SUPER, Z, Zed, exec, zed
bindd = SUPER, B, Brave, exec, brave-browser-nightly
bindd = SUPER, G, Gapless, exec, flatpak run com.github.neithern.g4music
bindd = SUPER, D, Discord, exec, flatpak run com.discordapp.Discord
bindd = SUPER ALT, S, Share, exec, localsend

# Volume control
bindle = , XF86AudioRaiseVolume, exec, ~/.config/hypr/scripts/osd.sh vol-up
bindle = , XF86AudioLowerVolume, exec, ~/.config/hypr/scripts/osd.sh vol-down
bindl  = , XF86AudioMute, exec, ~/.config/hypr/scripts/osd.sh vol-mute
bindl  = , XF86AudioMicMute, exec, ~/.config/hypr/scripts/osd.sh mic-mute
bindle = ALT, XF86AudioRaiseVolume, exec, ~/.config/hypr/scripts/osd.sh vol-up 1
bindle = ALT, XF86AudioLowerVolume, exec, ~/.config/hypr/scripts/osd.sh vol-down 1

# Screen Brightness
bindle = , XF86MonBrightnessUp, exec, ~/.config/hypr/scripts/osd.sh bright-up
bindle = , XF86MonBrightnessDown, exec, ~/.config/hypr/scripts/osd.sh bright-down
bindle = ALT, XF86MonBrightnessUp, exec, ~/.config/hypr/scripts/osd.sh bright-up 1
bindle = ALT, XF86MonBrightnessDown, exec, ~/.config/hypr/scripts/osd.sh bright-down 1

# Hyprscrolling
bind = SUPER, code:20, layoutmsg, colresize -0.1
bind = SUPER, code:21, layoutmsg, colresize +0.1
bind = SUPER, left, layoutmsg, move -col
bind = SUPER, right, layoutmsg, move +col
bind = SUPER CTRL, right, layoutmsg, movewindowto r
bind = SUPER CTRL, left, layoutmsg, movewindowto l
bind = SUPER CTRL, up, layoutmsg, movewindowto u
bind = SUPER CTRL, down, layoutmsg, movewindowto d
bind = SUPER, F, layoutmsg, fit active
bind = SUPER, X, layoutmsg, promote
bind = SUPER CTRL SHIFT, F, layoutmsg, fit tobeg
