source = $HOME/.config/omarchy/current/theme/hyprlock.conf

general {
    ignore_empty_input = true
}

animations {
    enabled = true
}

$accent = $font_color
$alt = $color
# $font = JetBrainsMono Nerd Font ExtraBold
# font_family = CaskaydiaMono Nerd Font ExtraBold
$font = Rhastelie

# GENERAL
general {
  hide_cursor = true
}

# BACKGROUND
background {
  monitor =
  path = $HOME/.config/omarchy/current/background
  blur_passes = 3
  color = $accent
}

# TIME
label {
  monitor =
  text = cmd[update:1000] date +"%I:%M:%S %p"
  color = $accent
  font_size = 150
  font_family = $font
  position = 0, -180
  halign = center
  valign = top
}

# DATE
label {
  monitor =
  text = cmd[update:1000] date +"%A, %d %B %Y"
  color = $accent
  font_size = 32
  font_family = $font
  position = 0, -480
  halign = center
  valign = top
}

# INPUT FIELD
input-field {
  monitor =
  size = 300, 60
  outline_thickness = 2
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  font_family = $font
  outer_color = $outer_color
  inner_color = $color
  font_color = $font_color
  fade_on_empty = false
  placeholder_text = $USER
  hide_input = false
  check_color = $check_color
  fail_color = $outer_color
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $color
  position = 0, -800
  halign = center
  valign = top
}
