general {
     gaps_in = 2
     gaps_out = 4
     border_size = 1
     col.active_border = rgba(cba6f766) rgba(cba6f728) 45deg
     col.inactive_border = rgba(11111b00)
     hover_icon_on_border = false
}

animations {
    enabled = yes

    bezier = multiBounce, 0.12, 1.15, 0.35, 1.0

    animation = windowsIn, 1, 4, multiBounce, slide bottom
    animation = windowsOut, 1, 6, multiBounce, slide bottom
}

decoration {
    rounding = 16
    rounding_power = 6.0
    active_opacity = 0.9
    inactive_opacity = 0.7

    shadow {
        enabled = true
        range = 12
        render_power = 3
        color = rgba(00000066)
    }

    blur {
        enabled = true
        size = 8
        passes = 2
        noise = 0.05
        new_optimizations = true
    }
}

layerrule = blur on, match:namespace swaync-control-center
layerrule = blur on, match:namespace swaync-notification-window

layerrule = ignore_alpha 0.5, match:namespace swaync-control-center
layerrule = ignore_alpha 0.5, match:namespace swaync-notification-window


windowrule = match:title ^(Library|File Upload|Open File|Save File|Select a Folder|Open Folder|Upload(.*)|Save As|Select File|Select Folder|Choose File|Sign in - Google Accounts — Zen Browser|Task Manager - Brave).*$, float on, size 700 500, center on
windowrule = match:class xdg-desktop-portal-gtk, float on, size 800 600, center on

windowrule = match:title ^(walker).*$, float on, size 300 300, center on

windowrule = match:title ^(Waypaper).*$, float on, size 900 600, center on

windowrule = size 400 500, match:class localsend

windowrule = match:title ^(Voice Recorder).*$, pin on, no_blur true, no_shadow true, border_size 0, opacity 1 1

layerrule = blur on, match:namespace ^(vicinae)$
layerrule = ignore_alpha 0.5, match:namespace ^(vicinae)$

