layerrule = blur on, match:namespace swaync-control-center
layerrule = blur on, match:namespace swaync-notification-window

layerrule = ignore_alpha 0.5, match:namespace swaync-control-center
layerrule = ignore_alpha 0.5, match:namespace swaync-notification-window


windowrule = match:title ^(Library|File Upload|Open File|Save File|Select a Folder|Open Folder|Upload(.*)|Save As|Select File|Select Folder|Choose File|Sign in - Google Accounts — Zen Browser|Task Manager - Brave).*$, float on, size 700 500, center on
windowrule = match:class xdg-desktop-portal-gtk, float on, size 800 600, center on

windowrule = match:title ^(walker).*$, float on, size 300 300, center on

windowrule = match:title ^(Waypaper).*$, float on, size 900 600, center on

windowrule = match:title ^(BLL-L22).*$, float on, center on, pin on

windowrule = size 400 500, match:class localsend

windowrule = match:title ^(Voice Recorder).*$, pin on, no_blur true, no_shadow true, border_size 0, opacity 1 1

layerrule = blur on, match:namespace ^(vicinae)$
layerrule = ignore_alpha 0.5, match:namespace ^(vicinae)$

