id = "catppuccin-blur"
name = "Catppuccin Blur"
version = "0.3.3"
schema_version = 1
description = "Catppuccin themes with blur"
repository = "https://github.com/jenslys/zed-catppuccin-blur"
authors = ["Jens Lystad <jens@lystad.io>"]
themes = ["themes/catppuccin-blur.json"]
icon_themes = []
languages = []
capabilities = []

[lib]

[grammars]

[language_servers]

[context_servers]

[agent_servers]

[slash_commands]
