general {
     gaps_in = 2
     gaps_out = 4
     border_size = 1
     col.active_border = rgba(cba6f766) rgba(cba6f728) 45deg
     col.inactive_border = rgba(11111b00)

    # Use master layout instead of dwindle
    # layout = master
}

decoration {
    rounding = 16
    rounding_power = 6.0
    active_opacity = 0.85
    inactive_opacity = 0.75

    shadow {
        enabled = true
        range = 12
        render_power = 3
        color = rgba(00000066)
    }

    blur {
        enabled = true
        size = 6
        passes = 2
    }
}

layerrule = blur on, match:namespace swaync-control-center
layerrule = blur on, match:namespace swaync-notification-window

layerrule = ignore_alpha 0.5, match:namespace swaync-control-center
layerrule = ignore_alpha 0.5, match:namespace swaync-notification-window

windowrule = match:title ^(Library|File Upload|Open File|Save File|Select a Folder|Open Folder|Upload(.*)|Save As|Select File|Select Folder|Choose File).*$, float on, size 700 500, center on

windowrule = match:class xdg-desktop-portal-gtk, float on, size 800 600, center on
