mode = "dark"

accent = "#9ba4bb"
cursor = "#d0cbb2"
foreground = "#d0cbb2"
background = "#080e15"
selection_foreground = "#080e15"
selection_background = "#d0cbb2"

color0 = "#21262c"
color1 = "#8c7666"
color2 = "#967150"
color3 = "#9a927a"
color4 = "#9ba4bb"
color5 = "#7d819c"
color6 = "#83a2a3"
color7 = "#d0cbb2"
color8 = "#63676c"
color9 = "#b39a85"
color10 = "#74543A"
color11 = "#c0b898"
color12 = "#c0c9e7"
color13 = "#a1a4c7"
color14 = "#a5c9ca"
color15 = "#dcd8c5"
