id = "nextjs-react-snippets"
name = "NEXTJS React JavaScript Snippets"
version = "0.1.0"
schema_version = 1
description = "A collection of useful NEXTJS + React + JavaScript snippets to speed up your development."
repository = "https://github.com/Konstantinos-Ps/zed-nextjs-react-snippets"
authors = ["Konstantinos Psychogios"]
themes = []
icon_themes = []
languages = []
snippets = "./snippets/jsx.json"
capabilities = []

[lib]

[grammars]

[language_servers]

[context_servers]

[slash_commands]

[indexed_docs_providers]
