id = "live-server"
name = "LiveServer"
version = "0.3.1"
schema_version = 1
description = "Launch a development local Server with live reload feature"
repository = "https://github.com/frederik-uni/zed-live-server"
authors = ["frederik <termite_pilgrim04@icloud.com>"]
themes = []
icon_themes = []
languages = []
capabilities = []

[lib]
kind = "Rust"
version = "0.1.0"

[grammars]

[language_servers.live-server]
language = "HTML"
languages = ["HTML", "JavaScript", "CSS"]

[language_servers.live-server.language_ids]
CSS = "css"
JavaScript = "javascript"
HTML = "html"

[context_servers]

[slash_commands]

[indexed_docs_providers]
