id = "comment"
name = "Comments Highlighter"
version = "0.6.6"
schema_version = 1
description = "Comment language extension for highlighting special comments"
repository = "https://github.com/thedadams/zed-comment"
authors = ["Donnie Adams <donnie@thedadams.com>"]
themes = []
icon_themes = []
languages = ["languages/comment"]
capabilities = []

[lib]

[grammars.comment]
repository = "https://github.com/thedadams/tree-sitter-comment"
rev = "3c25c172802fbb23c27580d77b1328c268beec43"

[language_servers]

[context_servers]

[agent_servers]

[slash_commands]
