id = "react-typescript-snippets"
name = "React Typescript Snippets"
version = "0.1.4"
schema_version = 1
description = "A collection of useful React + TypeScript snippets to speed up your development."
repository = "https://github.com/vishnuroshan/zed-react-ts-snippets"
authors = ["Vishnu Roshan"]
themes = []
icon_themes = []
languages = []
snippets = "./snippets/tsx.json"
capabilities = []

[lib]

[grammars]

[language_servers]

[context_servers]

[agent_servers]

[slash_commands]
